gains:
  pos: {x: 3.7, y: 3.7, z: 5.2}
  vel: {x: 2.4, y: 2.4, z: 3.0}
  rot: {x: 1.5, y: 1.5, z: 1.0}
  ang: {x: 0.13, y: 0.13, z: 0.1}
  ki:  {x: 0.0, y: 0.0, z: 0.03}

corrections:
  kf: 0.0e-08
  r: 0.0
  p: 0.0
